language: julia
os:
  - linux
#  - osx
# branches:
#   except:
#     - 0.7
julia:
  # - 0.7
  - nightly
notifications:
  email:
    on_success: never
    on_failure: never

# script:
#   - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#   - julia -e 'using Pkg; Pkg.add(pwd()); ENV["PYTHON"]=""; py="PyCall"; Pkg.add(py); Pkg.build(py); Pkg.test("DynamicalBilliards")'

after_success:
  - test $TRAVIS_OS_NAME = "linux" && julia -e 'using Pkg; Pkg.add("Documenter"); cd(Pkg.dir("DynamicalBilliards")); include(joinpath("docs", "make.jl"))'
#  - julia -e 'cd(Pkg.dir("DynamicalBilliards")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
#  - julia -e 'cd(Pkg.dir("DynamicalBilliards")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
